name: ASP.NET Core 3.1 + Tests + Azure App Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      CAMINHO_PROJETO_TESTES: ./APITemperatura.Testes/APITemperatura.Testes.csproj
      CAMINHO_PROJETO_WEBAPP: ./APITemperatura
      NOME_WEBAPP_AZURE: groffegithubactions

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

    - name: Build com o utilitario dotnet
      run: dotnet build ${{ env.CAMINHO_PROJETO_WEBAPP }} --configuration Release

    - name: Publish com o utilitario dotnet
      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBAPP }} -c Release -o app

    - name: Login no Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deployment no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP_AZURE }}
        package: './app'